[book]
authors = ["Eiger"]
language = "en"
multilingual = false
src = "src"
title = "The Polka Storage Book"
description = "The Polka Storage project aims to bring Filecoin-like storage to Polkadot!"

[output.html]
mathjax-support = true
